//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionStatu
    {
        public int AdmissionStatus_id { get; set; }
        public int ClassMaster_id { get; set; }
        public string AdmissionCode { get; set; }
        public Nullable<int> AdmissionStatus { get; set; }
        public Nullable<int> AdmissionSessionYear { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> FromDOB { get; set; }
        public Nullable<System.DateTime> TODOB { get; set; }
        public Nullable<int> ApplicaitonFees { get; set; }
        public Nullable<int> RegistrationFees { get; set; }
        public Nullable<int> Sessionyear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_ID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<bool> ISDeleted { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual ClassMaster ClassMaster { get; set; }
    }
}
