//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentTYPE
    {
        public int AssessmentType_Id { get; set; }
        public Nullable<int> AssessmentGroup_ID { get; set; }
        public string AssessmentType_code { get; set; }
        public string AssessmentType_Name { get; set; }
        public Nullable<int> MinMarks { get; set; }
        public Nullable<int> MaxMarks { get; set; }
        public Nullable<int> PassingMarks { get; set; }
        public string Weightage { get; set; }
        public Nullable<int> Sessionyear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Createdby_ID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int Modifiedby_ID { get; set; }
        public Nullable<int> School_ID { get; set; }
        public Nullable<int> Group_ID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
