//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentSubmissionDetail
    {
        public int DocumentSubmission_ID { get; set; }
        public Nullable<int> DocumentTypeID { get; set; }
        public Nullable<int> Enquiry_Id { get; set; }
        public string AdmissionNumber { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public string DigitalPathofDocument { get; set; }
        public string PhysicalFileLocaiton { get; set; }
        public Nullable<bool> onlinesubmitted { get; set; }
        public Nullable<bool> OnlineDocumentVerified { get; set; }
        public Nullable<int> Sessionyear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_ID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<bool> ISDeleted { get; set; }
    }
}
