//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster
    {
        public int EmployeeMasterID { get; set; }
        public string EmpCode { get; set; }
        public Nullable<int> EmpCategoryID { get; set; }
        public Nullable<int> StaffDesignationID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string ContactMobileNo { get; set; }
        public string HomePhone { get; set; }
        public string CurrentAddress { get; set; }
        public Nullable<int> CurrentCityID { get; set; }
        public Nullable<int> CurrentStateID { get; set; }
        public Nullable<int> CurrentCountryID { get; set; }
        public string CurrentPinCode { get; set; }
        public string CurrentLandmark { get; set; }
        public Nullable<bool> Is_also_Permanent { get; set; }
        public string PermenentAddress { get; set; }
        public Nullable<int> PermenentCity_ID { get; set; }
        public Nullable<int> PermenentState_ID { get; set; }
        public Nullable<int> PermenentCountry_ID { get; set; }
        public string PinCode { get; set; }
        public string Landmark { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string Nationality { get; set; }
        public Nullable<bool> Married { get; set; }
        public string Remarks { get; set; }
        public string FatheFirstName { get; set; }
        public string FatherMiddleName { get; set; }
        public string FatherLasttName { get; set; }
        public string MotherFirstName { get; set; }
        public string MotherMiddleName { get; set; }
        public string MotherLasttName { get; set; }
        public Nullable<int> Caste_ID { get; set; }
        public Nullable<int> Religon_ID { get; set; }
        public string Create_Login { get; set; }
        public string selectUsergroup { get; set; }
        public Nullable<int> EmpStatusId { get; set; }
        public Nullable<int> Sessionyear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Createdby_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby_ID { get; set; }
        public Nullable<int> School_ID { get; set; }
        public Nullable<int> Group_ID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
