//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndexScreenDetail
    {
        public int IndexScreenDetails_ID { get; set; }
        public Nullable<int> Nav_menu_ID { get; set; }
        public string TableName { get; set; }
        public string ColName { get; set; }
        public Nullable<bool> GridVisibilty { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<bool> Search_visible { get; set; }
        public string ColDataType { get; set; }
        public Nullable<bool> DefaultSorting { get; set; }
        public string DefaultSortOrder { get; set; }
        public Nullable<int> Sessionyear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Createdby_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby_ID { get; set; }
        public int School_ID { get; set; }
        public Nullable<int> Group_ID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual IndexScreenDetail IndexScreenDetails1 { get; set; }
        public virtual IndexScreenDetail IndexScreenDetail1 { get; set; }
    }
}
