//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumberGenScheme
    {
        public int NumberGenScheme_id { get; set; }
        public Nullable<int> NumGenForm_ID { get; set; }
        public string Prefix { get; set; }
        public string Postfix { get; set; }
        public string DateDisplayformat { get; set; }
        public Nullable<int> NumberStart { get; set; }
        public string Delimeter { get; set; }
        public Nullable<bool> IncludeDate { get; set; }
        public string Sequece { get; set; }
        public Nullable<int> Sessionyear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_ID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<bool> ISDeleted { get; set; }
        public Nullable<int> Navigationmenu_id { get; set; }
        public Nullable<int> NextNumber { get; set; }
        public Nullable<int> SchoolConfig_Id { get; set; }
    
        public virtual MasterTable MasterTable { get; set; }
        public virtual SchoolConfig SchoolConfig { get; set; }
        public virtual SchoolConfig SchoolConfig1 { get; set; }
        public virtual SchoolConfig SchoolConfig2 { get; set; }
        public virtual SchoolConfig SchoolConfig3 { get; set; }
    }
}
