//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteMaster
    {
        public int RouteMasterId { get; set; }
        public string RouteCode { get; set; }
        public string RoutName { get; set; }
        public Nullable<int> Totaldistance { get; set; }
        public Nullable<int> TripID { get; set; }
        public Nullable<int> VechicelID { get; set; }
        public Nullable<System.TimeSpan> MorningStartTime { get; set; }
        public Nullable<System.TimeSpan> AfternoonStarttime { get; set; }
        public Nullable<System.TimeSpan> MorningEndTime { get; set; }
        public Nullable<System.TimeSpan> AfternoonEndtime { get; set; }
        public Nullable<System.TimeSpan> TotalTriptime { get; set; }
        public Nullable<int> RouteCoordinator { get; set; }
        public Nullable<bool> ISAC { get; set; }
        public Nullable<int> Sessionyear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Createdby_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby_ID { get; set; }
        public int School_ID { get; set; }
        public int Group_ID { get; set; }
        public bool IsDeleted { get; set; }
    }
}
