//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SchoolConfig()
        {
            this.NumberGenSchemes = new HashSet<NumberGenScheme>();
            this.NumberGenSchemes1 = new HashSet<NumberGenScheme>();
            this.NumberGenSchemes2 = new HashSet<NumberGenScheme>();
            this.NumberGenSchemes3 = new HashSet<NumberGenScheme>();
        }
    
        public int SchoolConfig_id { get; set; }
        public Nullable<int> Navigationmenu_id { get; set; }
        public string tablecolumn { get; set; }
        public string configKey { get; set; }
        public string configvalue { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Sessionyear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_ID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<bool> ISDeleted { get; set; }
        public Nullable<int> NavigationMenuCode { get; set; }
    
        public virtual NavigationMenu1 NavigationMenu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberGenScheme> NumberGenSchemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberGenScheme> NumberGenSchemes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberGenScheme> NumberGenSchemes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberGenScheme> NumberGenSchemes3 { get; set; }
    }
}
