//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSLog
    {
        public int SmsLogId { get; set; }
        public string SmsLogCode { get; set; }
        public string ContactNumber { get; set; }
        public string SMS { get; set; }
        public Nullable<System.DateTime> SentTime { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> Sessionyear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_ID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<bool> ISDeleted { get; set; }
    }
}
