//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopMaster
    {
        public int StopMasterID { get; set; }
        public string StopCode { get; set; }
        public string StopName { get; set; }
        public string Locality { get; set; }
        public string StopAddress { get; set; }
        public string PinCode { get; set; }
        public string GeoCoordinates { get; set; }
        public Nullable<int> Sessionyear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Createdby_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby_ID { get; set; }
        public int School_ID { get; set; }
        public int Group_ID { get; set; }
        public bool IsDeleted { get; set; }
    }
}
