//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VechicleStaffMapping
    {
        public int VechicleStaffMappingID { get; set; }
        public Nullable<int> VechicleID { get; set; }
        public Nullable<int> DriveID { get; set; }
        public Nullable<int> Contuctor_1ID { get; set; }
        public Nullable<int> Conductor_2ID { get; set; }
        public Nullable<int> Sessionyear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Createdby_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby_ID { get; set; }
        public int School_ID { get; set; }
        public int Group_ID { get; set; }
        public bool IsDeleted { get; set; }
    }
}
