//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VechicleMaster
    {
        public int VechicleMasterId { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<int> VechicalManufactureNameID { get; set; }
        public Nullable<int> VechicalMakeID { get; set; }
        public Nullable<int> VechicalModelID { get; set; }
        public Nullable<int> Manufactureyear { get; set; }
        public string RegisteredOwner { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string RCImageIDpath { get; set; }
        public string VechicleImageIDPath { get; set; }
        public Nullable<int> TotalSeats { get; set; }
        public Nullable<int> FuelType { get; set; }
        public Nullable<int> VechicleStatusID { get; set; }
        public Nullable<int> Sessionyear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Createdby_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby_ID { get; set; }
        public int School_ID { get; set; }
        public int Group_ID { get; set; }
        public bool IsDeleted { get; set; }
    }
}
